# Generated by Django 5.0.3 on 2024-04-26 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
