# Generated by Django 5.0.3 on 2024-05-02 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_catastrophe_nom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catastrophe',
        ),
    ]
